### ISSUE TITLE
build 8.8

### ISSUE THREAD

**Issue by alembiq** [vrince/arm-beats#1]
Hi, can i ask you to generate release for beats 8.8 ?
No matter what I do inside my fork, I'm getting only 64bit build :( 

thanks

**Comment by vrince** [comment]
Sure, sorry I did not see your message :( make sure to @ me next time so there is more chance I see it :)

**Comment by vrince** [comment]
Here you have it : https://github.com/vrince/arm-beats/releases/tag/v8.8.2
